CREATE TABLE ITEM(ITEMNAME VARCHAR(50) NOT NULL UNIQUE,RATE FLOAT NOT NULL,QUANTITY INT NOT NULL)
CREATE TABLE CUSTOMER(FNAME VARCHAR(20) NOT NULL,LNAME VARCHAR(20) NOT NULL,PHONE bigint NOT NULL UNIQUE,EMAIL VARCHAR(50) NOT NULL UNIQUE)

SELECT * FROM ITEM
SELECT * FROM CUSTOMER

DROP TABLE ITEM
DROP TABLE CUSTOMER

CREATE PROCEDURE INSERTITEM @ITEMNAME VARCHAR(50),@RATE FLOAT,@QUANTITY INT AS BEGIN INSERT INTO ITEM VALUES(@ITEMNAME,@RATE,@QUANTITY) END
CREATE PROCEDURE UPDATEITEMRATE @ITEMNAME VARCHAR(50),@RATE FLOAT AS BEGIN UPDATE ITEM SET RATE = @RATE WHERE ITEMNAME = @ITEMNAME END
CREATE PROCEDURE UPDATEITEMQUANTITY @ITEMNAME VARCHAR(50),@QUANTITY INT AS BEGIN UPDATE ITEM SET QUANTITY = @QUANTITY WHERE ITEMNAME = @ITEMNAME END
CREATE PROCEDURE UPDATEITEMNAME @ITEMNAME VARCHAR(50),@NEWITEMNAME VARCHAR(50) AS BEGIN UPDATE ITEM SET ITEMNAME = @NEWITEMNAME WHERE ITEMNAME = @ITEMNAME END
CREATE PROCEDURE DELETEITEM @ITEMNAME VARCHAR(50) AS BEGIN DELETE FROM ITEM WHERE ITEMNAME = @ITEMNAME END
CREATE PROCEDURE SHOWALLITEMS AS BEGIN SELECT * FROM ITEM END

EXEC INSERTITEM 'RICE',50.5,10
EXEC UPDATEITEMRATE 'Rice',60
EXEC UPDATEITEMQUANTITY 'RICE',20
EXEC UPDATEITEMNAME 'RICE','DAAL'
EXEC DELETEITEM 'Daal'
EXEC SHOWALLITEMS

CREATE PROCEDURE INSERTCUSTOMER @FNAME VARCHAR(20),@LNAME VARCHAR(20),@PHONE bigint,@EMAIL VARCHAR(50) AS
BEGIN
IF ((@EMAIL LIKE '%[a-z,0-9]@[a-z]%.[A-Za-z]%[A-Za-z]') AND (@EMAIL NOT LIKE '%@%@%'))
INSERT INTO CUSTOMER VALUES(@FNAME,@LNAME,@PHONE,@EMAIL)
END
CREATE PROCEDURE UPDATECUSTOMERFNAME @EMAIL VARCHAR(50),@FNAME VARCHAR(20) AS BEGIN UPDATE CUSTOMER SET FNAME = @FNAME WHERE EMAIL = @EMAIL END
CREATE PROCEDURE UPDATECUSTOMERLNAME @EMAIL VARCHAR(50),@LNAME VARCHAR(20) AS BEGIN UPDATE CUSTOMER SET LNAME = @LNAME WHERE EMAIL = @EMAIL END
CREATE PROCEDURE UPDATECUSTOMERPHONE @EMAIL VARCHAR(50),@PHONE bigint AS BEGIN UPDATE CUSTOMER SET PHONE = @PHONE WHERE EMAIL = @EMAIL END
CREATE PROCEDURE UPDATECUSTOMEREMAIL @EMAIL VARCHAR(50),@NEWEMAIL VARCHAR(50) AS
BEGIN
IF ((@NEWEMAIL LIKE '%[a-z,0-9]@[a-z]%.[A-Za-z]%[A-Za-z]') AND (@NEWEMAIL NOT LIKE '%@%@%'))
UPDATE CUSTOMER SET EMAIL = @NEWEMAIL WHERE EMAIL = @EMAIL
END
CREATE PROCEDURE DELETECUSTOMER @EMAIL VARCHAR(50) AS BEGIN DELETE FROM CUSTOMER WHERE EMAIL = @EMAIL END
CREATE PROCEDURE SHOWALLCUSTOMERS AS BEGIN SELECT * FROM CUSTOMER END

EXEC INSERTCUSTOMER 'ABHAY','SINGH','4546456712','ABHAY@GMAIL.COM'
EXEC UPDATECUSTOMERFNAME 'ABHAY@GMAIL.COM','AKASH'
EXEC UPDATECUSTOMERLNAME 'ABHAY@GMAIL.COM','VERMA'
EXEC UPDATECUSTOMERPHONE 'ABHAY@GMAIL.COM',9874563210
EXEC UPDATECUSTOMEREMAIL 'ABHAY@GMAIL.COM','AKASH@GMAIL.COM'
EXEC DELETECUSTOMER 'AKASH@GMAIL.COM'
EXEC SHOWALLCUSTOMERS
