CREATE TABLE SUPERADMINDETAILS(SUPERID INT DEFAULT(1),USERNAME VARCHAR(50),LPASSWORD VARCHAR(50),POST VARCHAR(20) DEFAULT('SUPER ADMIN'))
CREATE TABLE ADMINDETAILS(ADMINID INT PRIMARY KEY IDENTITY(101,1),USERNAME VARCHAR(50) UNIQUE,LPASSWORD VARCHAR(50),FNAME VARCHAR(50),CITY VARCHAR(20),MNO VARCHAR(10) UNIQUE,POST VARCHAR(20) DEFAULT('ADMIN'))
CREATE TABLE CUSTOMERDETAILS(CUSTID INT PRIMARY KEY IDENTITY(1001,1),USERNAME VARCHAR(50) UNIQUE,LPASSWORD VARCHAR(50),FNAME VARCHAR(50),CITY VARCHAR(20),MNO VARCHAR(10) UNIQUE,POST VARCHAR(20) DEFAULT('CUSTOMER'))
CREATE TABLE VENUE(VENUEID INT PRIMARY KEY IDENTITY(10001,1), VENUENAME VARCHAR(50) UNIQUE,PRICEPERHOUR INT)
CREATE TABLE FOOD(FOODID INT,FOODNAME VARCHAR(50),FOREIGN KEY(FOODID) REFERENCES VENUE(VENUEID))
CREATE TABLE LIGHTS(LIGHTID INT,LIGHTNAME VARCHAR(50),FOREIGN KEY(LIGHTID) REFERENCES VENUE(VENUEID))
CREATE TABLE FLOWERS(FLOWERID INT,FLOWERNAME VARCHAR(50),FOREIGN KEY(FLOWERID) REFERENCES VENUE(VENUEID))
CREATE TABLE BOOKING(USERNAME VARCHAR(50),VENUENAME VARCHAR(50),BOOKINGDATE DATE,FROMTIME TIME, TOTIME TIME, FORPERSONS INT,STATUS VARCHAR(20) DEFAULT('NEUTRAL'))

SELECT * FROM SUPERADMINDETAILS
SELECT * FROM ADMINDETAILS
SELECT * FROM CUSTOMERDETAILS
SELECT * FROM VENUE
SELECT * FROM FOOD
SELECT * FROM LIGHTS
SELECT * FROM FLOWERS
SELECT * FROM BOOKING

drop table SUPERADMINDETAILS
drop table ADMINDETAILS
drop table CUSTOMERDETAILS
DROP TABLE VENUE
DROP TABLE FOOD
DROP TABLE LIGHTS
DROP TABLE FLOWERS
DROP TABLE BOOKING

Truncate table SUPERADMINDETAILS
Truncate table ADMINDETAILS
Truncate table CUSTOMERDETAILS
Truncate table VENUE
Truncate table FOOD
Truncate table LIGHTS
Truncate table FLOWERS
Truncate table BOOKING
select * from INFORMATION_SCHEMA.TABLES

